### ISSUE TITLE
Ready to use ? 

### ISSUE THREAD

**Issue by priscaure** [DanaDrimba/react-native-ingenico-sdk#1]
Hey Dana, 

I just came across your repo and I was wondering if it was ready to use ? 

It will literally save my life if it was ! I'm trying to implement Ingenico from scratch with my react native app for a client for weeks now, and I'm having a headache haha x 

Thank you in advance for your answer, 
Best regards, 

Prisca

**Comment by DanaDrimba** [comment]
Hi Prisca,

Thanks for writing. Please note that the repo is not production ready yet.
It is just something I have tried for our project. If you want, you can
fork it now, because most probably I will need top make it private until
stable and ready for prod. So feel free to use it with the mention that is
not prod ready.

Have fun! :)
Dana

**Comment by priscaure** [comment]
@DanaDrimba Thank you so much for answering !

Of course, I definitely understand, I'm forking it as we speak. 
Thank you for your time and best of luck with your project and to make this sdk prod ready :) 

Have a lovely day, 
Prisca

**Comment by priscaure** [comment]
Hi again Dana, 

I wanted to have play a little bit with your sdk but could you possibly put me on the right track on how to use this  ?
I already have my apikey etc ( from the ingenico sandbox, not preprod or prod)... and trying to start your sdk.

I see that that the startSDK function takes an object as an argument. It gives me an error when im creating an object with my Apikey and secret.  What I'm doing : 

`const session = {
      apiKey: <MyApiKey>,
      secretApiKey: <MySecret>',
};
IngenicoSdk.startSDK(session)`

Do I miss something, do I need more ? Do you have an example on how to start properly ? 
So sorry to bother you with this ^^
